### ISSUE TITLE
Ensure no Polymer elements used in Lovelace

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#2095]
All Lovelace elements should be using Lit. Goal of this issue is that this repo doesn't have Polymer elements, not the dependencies (that's for another issue).

To do:

- [x] cards/hui-entity-filter-card.js #2638
- [ ] cards/hui-history-graph-card.js #4882
- [x] cards/hui-map-card.js #2826 
- [x] cards/hui-plant-status-card.js #2891
- [x] cards/hui-weather-forecast-card.js #3623 
- [x] cards/hui-media-player-card.js #4761
- [x] components/hui-generic-entity-row.js #2636 
- [x] components/hui-image.js #2713 
- [x] components/notifications/hui-configurator-notification-item.js #3027
- [x] components/notifications/hui-notification-drawer.js
- [x] components/notifications/hui-notification-item-template.js #3029
- [x] components/notifications/hui-notification-item.js #3028
- [x] components/notifications/hui-notifications-button.js #2732
- [x] components/notifications/hui-persistent-notification-item.js #3032
- [x] entity-rows/hui-input-number-entity-row.js #2792
- [x] entity-rows/hui-timer-entity-row.js #2743
