### ISSUE TITLE
Rollup/WDS Work

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#5996]
In #5995 we introduced Rollup as an alternative bundler. This issue is to track remaining work:

## Fix
 - [ ] [ALL] Bundling of workers is not working anymore with [our plugin](https://github.com/home-assistant/frontend/blob/dev/build-scripts/rollup-plugins/worker-plugin.js) since we switched to Webpack 5 syntax.
       ```ts
       const worker = new Worker(new URL("./markdown_worker", import.meta.url));
       ```
    - [WDS only] This works if we add the extension to worker files. It requires:
      - Web Workers need to be on same domain, so we need to proxy all files via frontend. Possible with [this core branch](https://github.com/home-assistant/core/compare/frontend-dev) and update index.html to import from `/_dev_frontend/src/entrypoints/app.ts` etc.
      - This is module based so update `new Worker` with `{type: 'module'}` as 2nd arg`
      - Ran into issues with bundling the XSS package for markdown. Data filter worked fine.
      - Would also require to update webpack to use modules for web workers in dev mode or maybe add `IS_WDS` constant.
 - [ ] [Custom Panel] Update how we load custom panel entrypoint in empty iframe when bundling with Rollup and using ES5.
 - [ ] [Hassio] Supervisor build needs to load the SystemJS loader when loading the ES5 build
 - [ ] [ALL] ES5 build is broken. RegeneratorRuntime is not set on window in compatibility.js.
 - [ ] [Rollup] Figure out why scoped element registry doesn't work (bypassed in #15631)
 - [x] [ALL] `new Fuse()` doesn't work. In Rollup object is `{default:constructor}` #6012
 - [x] [Rollup config] Rollup config handling of `bundle.ignorePackages` + `bundle.emptyPackages` doesn't work (to test: build demo -> see app.js)  #6007
 - [x] [Gallery] remove using dynamic `require()` call to list a dir and its files because Rollup doesn't support it #6203
 - [x] [ALL] Update check to serve which version to rely on support of `import()` function instead of support of `modules`. (app already done)
 - [ ] Check if we need to replace `lit-virtualizer/lib/uni-virtualizer/lib/polyfillLoaders/EventTarget.js` like we did for Webpack (`src/resources/EventTarget-ponyfill.js`)

## Clean up
 - [x] [build-scripts] Move `babel.js` options into `bundle.js` #5997
 - [x] [build-scripts] Any constant in `build-scripts` that refers packages with `require.resolve` needs to be returned from a function #5997
 - [x] [build-scripts] Prefix app variables in `build-scripts/paths.js` with `app_` #5997

## Improve
 - [ ] [App] split out authorize, onboarding and core into their own bundle config so they don't mess with the chunks of app. 
 - [ ] [App] Clean up chunks with [manualChunks](https://rollupjs.org/guide/en/#manualchunks) (first split out stuff)
 - [x] [Rollup worker plugin] add the worker source code to the Rollup watchlist for in dev #6034
 - [x] [Rollup worker plugin] add `terser` to default plugins to copy over so we minify workers in prod builds  #6011
 - [x] [App] When building a latest build, empty out the `proxy-polyfill` package  #6011

## Explore
 - [ ] [App] ~~Can we move import of `home-assistant-main.ts` out of `home-assistant.ts` to define the `home-assistant` element earlier and start doing work?~~ Since it's 1 JS file it won't benefit.
 - [ ] [Rollup] Can we speed up loading with [rollup-plugin-hoist-import-deps](https://github.com/vikerman/rollup-plugin-hoist-import-deps) with `import()` syntax.
 - [ ] [Bundlers] Allow marking imports as side effect free to optimize bundling. For Rollup, pass a function to [`treeshake.moduleSideEffects`](https://rollupjs.org/guide/en/#treeshake)
 - [ ] [Rollup - ES5] Use System.js [named-register extra](https://github.com/systemjs/systemjs/blob/master/src/extras/named-register.js) to create a self executing System JS script. Can we turn this into a Rollup plugin?
    ```js
    SystemJSRegisterNamed({
      // Entry per entrypoint name.
      // Each entry will get named after their public path.
      // Value is true or extra options
      core: true,
      app: {
        // If script needs to import itself as last call.
        // System.register("frontend_es5/app.js", …); System.import("frontend_es5/app.js");
        importSelf: true,
        // Inject dependencies on other entrypoints
        addEntrypointDependencies: ["core"]
      }
    })
    ```
 - [x] [App] Can we merge compatibility entry point into core and empty it on latest build? #6029
 - [x] [Webpack] Upgrade to Webpack 5 (beta) to see improvements #6200
 - [x] [Rollup] ~~Replace terser plugin with [closure-compiler](https://github.com/ampproject/rollup-plugin-closure-compiler/blob/master/README.md)~~ My mac with 16GB runs out of memory when I tried.

## Finally
- [ ] Remove Webpack packages
- [ ] Remove Webpack ES5 loading logic in HTML templates
- [x] Document build goals and how it works
- [x] Document breaking change: updated minimum requirement to use latest build of the frontend ([old](https://caniuse.com/#feat=es6-module), [new](https://caniuse.com/#feat=es6-module-dynamic-import)).

**Comment by balloob** [comment]
Still some fixes left.

**Comment by rob-mccann** [comment]
I've been playing around with this a little and noticed the compression task taking a while - I think we can shave a few minutes off the `build_frontend` job by compressing as part of the tasks rather than as a separate job afterwards (reduces disk io).

**Comment by balloob** [comment]
We have split out the compression task to separate concerns. We want the bundler to bundle. Generating service workers, compression, entrypoint HTML pages etc are all done in different tasks. We also avoid compression on CI and during dev, so it's not very impactful.

**Comment by balloob** [comment]
Yaaaaaaaaa

**Comment by bnb** [comment]
> Still in process, might never finish :D

might be worth dropping Rollup at this point :P
